services:
  - type: web
    name: ips-app
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python run_app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.12.11"