"""Single-source proposal preview renderer for the Estimating module.

Design principle: ONE preview system
-------------------------------------
All on-screen proposal preview rendering delegates to the canonical helpers in
``app.estimate.proposal_preview_tab``:

  * ``build_proposal_tab_estimate_data()``  — builds the data dict
  * ``build_proposal_html()``               — HTML card (used by Proposal tab and
                                              Review/Save tab in editor.py)
  * ``render_proposal_document_preview()``  — renders the HTML card via st.html
  * ``render_proposal_tab()``               — show/hide toggle + preview panel

The editor's Review/Save tab calls ``render_proposal_export_actions()`` directly
(download buttons only, no second preview).  Both tabs use the same
``build_proposal_tab_estimate_data()`` → ``build_proposal_html()`` pipeline so
the on-screen preview always matches the exported Word document.

Proposal title ("Project" label)
---------------------------------
``build_proposal_view_model()`` in ``proposal_document_layout.py`` resolves the
title token:
  1. ``est["estimate_description"]`` (the "Estimate Description" / "Project" field)
  2. Job name from the linked job row
  3. Literal string ``"Project"``

The resolved token is stored under ``estimate_data["estimate_description"]`` in
the data dict returned by ``build_proposal_tab_estimate_data()``.  ``build_proposal_html()``
uses it as the banner title, matching the Word ``{{JOB_NAME}}`` placeholder.

Customer location
-----------------
Customer location is intentionally **excluded** from all proposal/preview output
(not printed in Word template, not in ``build_proposal_html``).  The only use
of ``customer_location_id`` in the proposal pipeline is to scope contact lookup
(``proposal_exports._proposal_contact_name_for_export``) — not to print an
address line.
"""
from __future__ import annotations

from typing import Any


# ---------------------------------------------------------------------------
# Data-building helpers
# ---------------------------------------------------------------------------

def build_estimate_data_for_preview(
    est: dict[str, Any],
    totals: dict[str, Any],
    pe: dict[str, Any],
    *,
    docx_bytes: bytes | None = None,
    pdf_bytes: bytes | None = None,
    word_error: str = "",
    loaded_estimate_id: str | None = None,
    is_locked: bool = False,
) -> dict[str, Any]:
    """Build the canonical proposal data dict for preview and export.

    ``pe`` must contain: customer_name, job_name, contact_name, prepared_by_phone.
    These are typically produced by ``export.get_proposal_export_kwargs()``.

    Both the Proposal tab and the Review/Save tab should call this function to
    guarantee they show identical content.
    """
    from app.estimate.proposal_preview_tab import build_proposal_tab_estimate_data

    return build_proposal_tab_estimate_data(
        est,
        totals,
        pe,
        docx_bytes=docx_bytes,
        pdf_bytes=pdf_bytes,
        word_error=word_error,
        loaded_estimate_id=loaded_estimate_id,
        is_locked=is_locked,
    )


# ---------------------------------------------------------------------------
# Rendering helpers (all delegate to proposal_preview_tab — no duplication)
# ---------------------------------------------------------------------------

def render_estimate_preview(estimate_data: dict[str, Any]) -> None:
    """Render the on-screen HTML card preview (Proposal tab and Review/Save tab).

    The HTML is generated by ``build_proposal_html()`` in proposal_preview_tab,
    which uses the same field mapping as the Word template, so the preview
    matches the exported document.  Customer location is not shown.
    """
    from app.estimate.proposal_preview_tab import render_proposal_document_preview

    render_proposal_document_preview(estimate_data)


def render_proposal_tab(estimate_data: dict[str, Any]) -> None:
    """Proposal tab: show/hide toggle + HTML preview panel.

    Delegates directly to the canonical ``render_proposal_tab`` in
    ``proposal_preview_tab.py``.
    """
    from app.estimate.proposal_preview_tab import render_proposal_tab as _render

    _render(estimate_data)


def build_proposal_html_string(estimate_data: dict[str, Any]) -> str:
    """Return the proposal HTML string for the on-screen card preview.

    Delegates to ``build_proposal_html()`` in proposal_preview_tab.
    The returned HTML uses the same field values as the Word export.
    """
    from app.estimate.proposal_preview_tab import build_proposal_html

    return build_proposal_html(estimate_data)
