"""Explicit PostgREST column projections for list reads (avoids ``select('*')``)."""

from __future__ import annotations

# Only for inferring live column keys from a sample row (schema drift helpers).
SCHEMA_INTROSPECTION_COLUMNS = "*"


def _cols(*names: str) -> str:
    return ",".join(names)


JOBS_COLUMNS = _cols(
    "id",
    "customer_id",
    "customer_location_id",
    "location_id",
    "customer_contact_id",
    "estimate_id",
    "job_number",
    "job_name",
    "customer_name",
    "location",
    "status",
    "project_manager",
    "supervisor",
    "supervisor_id",
    "start_date",
    "end_date",
    "target_completion_date",
    "completed_date",
    "percent_complete",
    "awarded_amount",
    "estimated_cost",
    "actual_cost",
    "projected_gross_profit",
    "projected_margin_pct",
    "billing_type",
    "scope_of_work",
    "notes",
    "source_type",
    "estimate_number",
    "source_estimate_number",
    "approved_at",
    "approved_by",
    "po_number",
    "po_date",
    "po_amount",
    "is_deleted",
    "completed_at",
    "cancelled_at",
    "deleted_at",
    "created_at",
    "updated_at",
)

ESTIMATES_LIST_COLUMNS = _cols(
    "id",
    "customer_id",
    "customer_location_id",
    "customer_contact_id",
    "job_id",
    "quote_number",
    "estimate_number",
    "customer_name",
    "project_name",
    "job_name",
    "status",
    "estimate_date",
    "expiration_date",
    "description",
    "scope_of_work",
    "customer_responsibilities",
    "notes",
    "revision_number",
    "created_at",
    "updated_at",
    "created_by",
    "prepared_by_name",
    "subtotal",
    "total_cost",
    "total",
    "grand_total",
    "material_cost",
    "material_total",
    "labor_cost",
    "labor_total",
    "equipment_cost",
    "equipment_total",
    "travel_cost",
    "travel_markup",
    "travel_price",
    "travel_total",
    "subcontractor_cost",
    "other_cost",
    "tax",
    "tax_amount",
    "tax_rate",
    "markup",
    "total_markup",
    "taxable_subtotal",
    "customer_price",
    "gross_profit",
    "gross_margin_percent",
    "default_material_markup_pct",
    "default_labor_markup_pct",
    "default_equipment_markup_pct",
    "default_travel_markup_pct",
    "default_subcontractor_markup_pct",
    "default_other_markup_pct",
    "global_markup_pct",
    "overhead_pct",
    "profit_pct",
    "proposal_show_line_items",
    "proposal_show_category_totals",
    "proposal_show_final_price_only",
    "approved_at",
    "approved_by",
    "archived_from_estimates",
    "converted_to_job_at",
)

CUSTOMERS_COLUMNS = _cols(
    "id",
    "customer_name",
    "customer_code",
    "status",
    "is_active",
    "phone",
    "email",
    "billing_address",
    "notes",
    "created_at",
    "updated_at",
)

CUSTOMER_LOCATIONS_COLUMNS = _cols(
    "id",
    "customer_id",
    "location_name",
    "address",
    "city",
    "state",
    "zip",
    "status",
    "is_active",
    "is_primary",
    "notes",
    "created_at",
    "updated_at",
)

CUSTOMER_CONTACTS_COLUMNS = _cols(
    "id",
    "customer_id",
    "customer_location_id",
    "contact_name",
    "name",
    "email",
    "phone",
    "title",
    "role",
    "status",
    "is_active",
    "is_primary",
    "notes",
    "created_at",
    "updated_at",
)

INVENTORY_ITEMS_COLUMNS = _cols(
    "id",
    "item_name",
    "name",
    "sku",
    "barcode",
    "category",
    "storage_location",
    "stock_location",
    "location",
    "department",
    "status",
    "quantity_on_hand",
    "qty_on_hand",
    "quantity_allocated",
    "quantity_available",
    "quantity_checked_out",
    "reorder_point",
    "unit_cost",
    "last_purchase_cost",
    "average_cost",
    "vendor",
    "vendor_id",
    "vendor_name",
    "description",
    "pricing_guide_id",
    "pricing_item_id",
    "taxable",
    "is_active",
    "qr_code_value",
    "qr_token",
    "image_path",
    "image_url",
    "photo_url",
    "thumbnail_url",
    "photo_path",
    "image_file_name",
    "image_mime_type",
    "image_uploaded_at",
    "image_uploaded_by",
    "image_status",
    "created_at",
    "updated_at",
)

ASSETS_COLUMNS = _cols(
    "id",
    "asset_id",
    "asset_number",
    "asset_tag",
    "asset_name",
    "name",
    "category",
    "asset_type",
    "location",
    "department",
    "status",
    "condition",
    "acquired_date",
    "purchase_date",
    "value",
    "purchase_cost",
    "purchase_price",
    "current_value",
    "serial_number",
    "manufacturer",
    "model_number",
    "model",
    "operator",
    "assigned_to",
    "assigned_employee",
    "assigned_trailer_id",
    "assigned_job_id",
    "job_id",
    "service_due",
    "next_service_due",
    "maintenance_due_date",
    "inspection_due",
    "pricing_guide_id",
    "pricing_item_id",
    "description",
    "notes",
    "primary_use",
    "hours_miles",
    "last_used",
    "last_used_at",
    "salvage_value",
    "depreciation_method",
    "useful_life",
    "annual_depreciation",
    "qr_code_value",
    "qr_token",
    "qr_value",
    "is_rental",
    "is_rentable",
    "include_in_pricing_guide",
    "rental_daily_rate",
    "rental_weekly_rate",
    "rental_monthly_rate",
    "rental_rate_unit",
    "rental_default_markup_percent",
    "rental_notes",
    "hourly_rate",
    "daily_rate",
    "weekly_rate",
    "image_path",
    "image_url",
    "image_file_name",
    "image_mime_type",
    "image_uploaded_at",
    "image_uploaded_by",
    "image_status",
    "photo_path",
    "photo_url",
    "is_kit",
    "kit_type",
    "kit_status",
    "total_kit_value",
    "last_kit_audit_at",
    "assigned_to_employee_id",
    "assigned_to_name",
    "assigned_to_phone",
    "is_serialized_tool",
    "is_checkout_item",
    "tracking_type",
    "created_at",
    "updated_at",
)

EMPLOYEES_COLUMNS = _cols(
    "id",
    "name",
    "email",
    "phone",
    "username",
    "position",
    "trade",
    "role",
    "hire_date",
    "employee_number",
    "department",
    "status",
    "is_active",
    "is_employee",
    "deleted_at",
    "auth_user_id",
    "profile_id",
    "hourly_rate",
    "overtime_rate",
    "notes",
    "created_at",
    "updated_at",
)

PROFILES_COLUMNS = _cols(
    "id",
    "email",
    "full_name",
    "role",
    "is_active",
    "phone",
    "created_at",
    "updated_at",
)

LABOR_RATES_COLUMNS = _cols(
    "id",
    "classification",
    "role",
    "rate",
    "hourly_rate",
    "overtime_rate",
    "burden_rate",
    "is_active",
    "notes",
    "created_at",
    "updated_at",
)

ESTIMATE_LINE_ITEMS_COLUMNS = _cols(
    "id",
    "estimate_id",
    "inventory_item_id",
    "pricing_item_id",
    "pricing_guide_id",
    "item_number",
    "item_key",
    "sku",
    "description",
    "category",
    "qty",
    "quantity",
    "unit",
    "unit_cost",
    "purchase_price",
    "total_cost",
    "line_total",
    "markup",
    "markup_percent",
    "markup_amount",
    "price_total",
    "taxable",
    "vendor",
    "vendor_id",
    "notes",
    "sort_order",
    "created_at",
    "updated_at",
)

PRICING_GUIDE_ITEMS_COLUMNS = _cols(
    "id",
    "item_code",
    "item_type",
    "item_class",
    "description",
    "category",
    "subcategory",
    "unit",
    "default_cost",
    "default_markup_percent",
    "default_sell_price",
    "markup_percent",
    "sell_price",
    "taxable",
    "is_active",
    "inventory_item_id",
    "asset_id",
    "linked_inventory_id",
    "linked_asset_id",
    "vendor_id",
    "vendor",
    "labor_role",
    "equipment_type",
    "travel_type",
    "notes",
    "item_number",
    "model_number",
    "sku",
    "image_path",
    "image_url",
    "image_file_name",
    "image_status",
    "qr_code_url",
    "stock_policy",
    "default_reorder_point",
    "default_reorder_quantity",
    "fitting_category",
    "fitting_connection",
    "created_at",
    "updated_at",
)

PRICING_GUIDE_PRICE_HISTORY_COLUMNS = _cols(
    "id",
    "pricing_item_id",
    "old_cost",
    "new_cost",
    "changed_by",
    "changed_at",
    "notes",
)

VENDORS_COLUMNS = _cols(
    "id",
    "vendor_name",
    "name",
    "contact_name",
    "email",
    "phone",
    "is_active",
    "notes",
    "created_at",
    "updated_at",
)

TODOS_COLUMNS = _cols(
    "id",
    "title",
    "status",
    "priority",
    "assigned_to",
    "assignee_name",
    "assigned_to_email",
    "assignee_email",
    "assigned_to_employee_id",
    "assignee_id",
    "job_id",
    "estimate_id",
    "job_label",
    "linked_job",
    "estimate_label",
    "linked_estimate",
    "due_date",
    "description",
    "notes",
    "created_at",
    "updated_at",
)

TIME_ENTRIES_COLUMNS = _cols(
    "id",
    "employee_id",
    "job_id",
    "work_date",
    "hours",
    "time_type",
    "non_job_code",
    "notes",
    "approved",
    "status",
    "created_by",
    "created_at",
    "updated_at",
)

EMPLOYEE_TIMEKEEPING_DAYS_COLUMNS = _cols(
    "id",
    "employee_id",
    "work_date",
    "week_start",
    "status",
    "hours_st",
    "hours_ot",
    "hours_dt",
    "total_hours",
    "notes",
    "approved_by",
    "approved_at",
    "created_at",
    "updated_at",
    "st_hours",
    "ot_hours",
    "dt_hours",
    "job_label",
    "job_id",
    "calculated_time_type",
    "final_time_type",
    "overtime_override",
    "overtime_override_by",
    "overtime_override_at",
    "overtime_override_reason",
)

EMPLOYEE_TIMEKEEPING_WEEKS_COLUMNS = _cols(
    "id",
    "employee_id",
    "week_start",
    "week_end",
    "status",
    "total_hours",
    "notes",
    "approved_by",
    "approved_at",
    "created_at",
    "updated_at",
)

JOB_EQUIPMENT_COLUMNS = _cols(
    "id",
    "job_id",
    "asset_id",
    "asset_label",
    "usage_hours",
    "usage_days",
    "rate_per_hour",
    "rate_per_day",
    "line_total",
    "notes",
    "created_at",
    "updated_at",
)

JOB_EMAIL_SETTINGS_COLUMNS = _cols(
    "id",
    "job_id",
    "enabled",
    "recipient_emails",
    "send_day",
    "last_sent_at",
    "created_at",
    "updated_at",
)

INVENTORY_TRANSACTIONS_COLUMNS = _cols(
    "id",
    "inventory_item_id",
    "job_id",
    "subjob_id",
    "transaction_type",
    "quantity",
    "qty",
    "unit",
    "previous_quantity",
    "new_quantity",
    "destination_type",
    "notes",
    "scanned_by_user_id",
    "scanned_by_name",
    "scanned_by_phone",
    "scanned_by_employee_id",
    "phone_verified",
    "device_label",
    "device_info",
    "source",
    "created_by",
    "created_at",
)

EMPLOYEE_DOCUMENTS_COLUMNS = _cols(
    "id",
    "employee_id",
    "document_type",
    "file_name",
    "storage_path",
    "uploaded_at",
    "uploaded_by",
    "notes",
    "created_at",
    "updated_at",
)

COMPANY_EVENTS_COLUMNS = _cols(
    "id",
    "title",
    "event_date",
    "category",
    "description",
    "location",
    "created_at",
    "updated_at",
)

EMPLOYEE_CERTIFICATIONS_COLUMNS = _cols(
    "id",
    "employee_id",
    "cert_type",
    "certification_type",
    "type",
    "cert_number",
    "certification_number",
    "number",
    "issuer",
    "issuing_organization",
    "issue_date",
    "expiration_date",
    "status",
    "attachment_path",
    "attachment_url",
    "attachment_file_name",
    "attachment_mime_type",
    "attachment_uploaded_at",
    "attachment_uploaded_by",
    "notes",
    "created_at",
    "updated_at",
)

DOCUMENTS_HUB_COLUMNS = _cols(
    "id",
    "file_name",
    "document_type",
    "doc_type",
    "category",
    "upload_date",
    "created_at",
    "uploaded_by",
    "is_restricted",
    "storage_path",
    "notes",
)

COMPANY_UPDATES_COLUMNS = _cols(
    "id",
    "title",
    "category",
    "status",
    "body",
    "content",
    "published_at",
    "created_at",
    "updated_at",
    "author",
    "notes",
    "banner_path",
    "banner_file_name",
    "banner_mime_type",
    "banner_caption",
    "banner_uploaded_at",
)

WEEKLY_TIMESHEETS_COLUMNS = _cols(
    "id",
    "job_id",
    "customer_id",
    "week_start",
    "week_end",
    "job_number",
    "client_name",
    "job_name",
    "po_number",
    "sheet_date",
    "work_performed",
    "approved_by",
    "approved_by_name",
    "approved_by_title",
    "approved_at",
    "status",
    "pdf_path",
    "pdf_url",
    "pdf_file_url",
    "unsigned_pdf_url",
    "excel_path",
    "excel_url",
    "signed_at",
    "signed_by_name",
    "signed_by_email",
    "sign_token",
    "sign_token_expires_at",
    "locked_at",
    "created_by",
    "created_at",
    "updated_at",
)

WEEKLY_TIMESHEET_LINES_COLUMNS = _cols(
    "id",
    "timesheet_id",
    "line_type",
    "sort_order",
    "description",
    "class_name",
    "employee_equipment",
    "employee_id",
    "asset_id",
    "inventory_item_id",
    "hours_mon",
    "hours_tue",
    "hours_wed",
    "hours_thu",
    "hours_fri",
    "hours_sat",
    "hours_sun",
    "st_hours",
    "ot_hours",
    "dt_hours",
    "rate",
    "amount",
    "notes",
)

JOB_DAILY_UPDATES_COLUMNS = _cols(
    "id",
    "job_id",
    "update_date",
    "employee_id",
    "employee_name",
    "supervisor_id",
    "supervisor_name",
    "work_performed",
    "summary",
    "notes",
    "delays",
    "safety_notes",
    "weather",
    "created_by",
    "created_at",
    "updated_at",
)

JOB_MATERIALS_COLUMNS = _cols(
    "id",
    "job_id",
    "inventory_item_id",
    "pricing_guide_id",
    "item_name",
    "quantity",
    "unit_cost",
    "line_total",
    "subjob_id",
    "employee_id",
    "inventory_transaction_id",
    "used_at",
    "usage_source",
    "destination_type",
    "notes",
    "created_at",
    "updated_at",
)

SMALL_HAND_TOOLS_COLUMNS = _cols(
    "id",
    "tool_name",
    "category",
    "description",
    "quantity_on_hand",
    "quantity_expected",
    "unit",
    "unit_value",
    "storage_type",
    "container_asset_id",
    "storage_location",
    "assigned_job_id",
    "status",
    "condition",
    "model_number",
    "serial_number",
    "notes",
    "is_active",
    "created_at",
    "updated_at",
)

TOOL_TRANSACTIONS_COLUMNS = _cols(
    "id",
    "tool_id",
    "transaction_type",
    "employee_id",
    "job_id",
    "notes",
    "created_at",
)

COMPANY_SETTINGS_COLUMNS = _cols(
    "id",
    "company_name",
    "logo_storage_path",
    "timezone",
    "default_landing_page",
    "date_format",
    "email_notifications_enabled",
    "timekeeping_weekend_counts_toward_40",
    "created_at",
    "updated_at",
)

IPS_LOOKUP_TABLES_COLUMNS = _cols(
    "id",
    "slug",
    "label",
    "description",
    "sort_order",
    "created_at",
)

IPS_LOOKUP_VALUES_COLUMNS = _cols(
    "id",
    "lookup_table_id",
    "value",
    "sort_order",
    "is_active",
    "created_at",
)

TOOL_TRAILER_KITS_COLUMNS = _cols(
    "id",
    "trailer_name",
    "supervisor",
    "qr_code",
    "location",
    "assigned_job_id",
    "parent_asset_id",
    "notes",
    "is_active",
    "created_at",
    "updated_at",
)

ASSET_KIT_ITEMS_COLUMNS = _cols(
    "id",
    "parent_asset_id",
    "child_asset_id",
    "item_name",
    "item_type",
    "category",
    "description",
    "quantity",
    "quantity_expected",
    "quantity_actual",
    "unit",
    "unit_value",
    "total_value",
    "replacement_cost",
    "expected_life_days",
    "last_replaced_at",
    "replacement_count",
    "inventory_item_id",
    "condition",
    "status",
    "serial_number",
    "qr_code_value",
    "qr_token",
    "qr_value",
    "assigned_to_employee_id",
    "assigned_to_name",
    "is_active",
    "notes",
    "created_at",
    "updated_at",
)

ASSET_KIT_AUDITS_COLUMNS = _cols(
    "id",
    "parent_asset_id",
    "audit_date",
    "performed_by_user_id",
    "performed_by_employee_id",
    "performed_by_name",
    "performed_by_phone",
    "assigned_supervisor_id",
    "assigned_supervisor_name",
    "job_id",
    "expected_item_count",
    "present_item_count",
    "missing_item_count",
    "damaged_item_count",
    "expected_value",
    "missing_value",
    "damaged_value",
    "status",
    "notes",
    "created_at",
)

ASSET_KIT_TRANSACTIONS_COLUMNS = _cols(
    "id",
    "parent_asset_id",
    "kit_item_id",
    "job_id",
    "transaction_type",
    "quantity",
    "performed_by_user_id",
    "performed_by_employee_id",
    "performed_by_name",
    "performed_by_phone",
    "assigned_to_employee_id",
    "assigned_to_name",
    "previous_status",
    "new_status",
    "notes",
    "created_at",
)

ESTIMATE_LABOR_LINES_COLUMNS = _cols(
    "id",
    "estimate_id",
    "description",
    "labor_type",
    "role_name",
    "employee_id",
    "hours",
    "rate",
    "total",
    "st_hours",
    "ot_hours",
    "dt_hours",
    "st_rate",
    "ot_rate",
    "dt_rate",
    "cost_total",
    "markup_percent",
    "markup_amount",
    "price_total",
    "notes",
    "sort_order",
    "created_at",
)

ESTIMATE_EQUIPMENT_COLUMNS = _cols(
    "id",
    "estimate_id",
    "asset_id",
    "equipment_name",
    "equipment_type",
    "quantity",
    "duration",
    "duration_unit",
    "cost_rate",
    "cost_total",
    "markup_percent",
    "markup_amount",
    "price_total",
    "notes",
    "sort_order",
    "created_at",
)

ESTIMATE_SUBCONTRACTORS_COLUMNS = _cols(
    "id",
    "estimate_id",
    "vendor_id",
    "subcontractor_name",
    "description",
    "cost_total",
    "markup_percent",
    "markup_amount",
    "price_total",
    "notes",
    "sort_order",
    "created_at",
)

ESTIMATE_OTHER_COSTS_COLUMNS = _cols(
    "id",
    "estimate_id",
    "description",
    "category",
    "cost_total",
    "markup_percent",
    "markup_amount",
    "price_total",
    "taxable",
    "notes",
    "sort_order",
    "created_at",
)

ESTIMATE_TRAVEL_COLUMNS = _cols(
    "id",
    "estimate_id",
    "travel_type",
    "description",
    "origin",
    "destination",
    "miles",
    "mileage_rate",
    "trips",
    "people",
    "travel_hours",
    "hourly_rate",
    "nights",
    "lodging_rate",
    "per_diem_days",
    "per_diem_rate",
    "airfare_cost",
    "rental_vehicle_cost",
    "fuel_cost",
    "parking_tolls_cost",
    "other_cost",
    "cost_total",
    "markup_percent",
    "markup_amount",
    "price_total",
    "taxable",
    "notes",
    "sort_order",
    "created_at",
    "updated_at",
)

ESTIMATE_TERMS_COLUMNS = _cols(
    "id",
    "name",
    "terms_text",
    "is_default",
    "created_at",
)

QR_SCAN_EVENTS_COLUMNS = _cols(
    "id",
    "created_at",
    "qr_value",
    "item_type",
    "item_name",
    "inventory_item_id",
    "asset_id",
    "result",
    "action_taken",
    "job_id",
    "destination_type",
    "scanned_by_user_id",
    "scanned_by_name",
    "scanned_by_phone",
    "employee_id",
    "device_label",
    "source",
    "error_message",
    "inventory_transaction_id",
    "tool_transaction_id",
    "quantity",
    "unit",
)

ASSET_INSPECTIONS_COLUMNS = _cols(
    "id",
    "asset_id",
    "inspection_type",
    "inspection_date",
    "inspector",
    "status",
    "issues_found",
    "corrective_action",
    "photo_path",
    "created_by",
    "created_at",
)

# Legacy / alternate table names used in fetch_rows alt_tables=.
TABLE_ALIASES: dict[str, str] = {
    "inventory": "inventory_items",
    "asset_database": "assets",
    "contacts": "customer_contacts",
    "tasks": "todos",
    "estimate_materials": "estimate_line_items",
    "certifications": "employee_certifications",
    "documents": "documents_hub",
    "timekeeping": "employee_timekeeping_weeks",
}

TABLE_LIST_COLUMNS: dict[str, str] = {
    "jobs": JOBS_COLUMNS,
    "estimates": ESTIMATES_LIST_COLUMNS,
    "customers": CUSTOMERS_COLUMNS,
    "customer_locations": CUSTOMER_LOCATIONS_COLUMNS,
    "customer_contacts": CUSTOMER_CONTACTS_COLUMNS,
    "inventory_items": INVENTORY_ITEMS_COLUMNS,
    "assets": ASSETS_COLUMNS,
    "employees": EMPLOYEES_COLUMNS,
    "profiles": PROFILES_COLUMNS,
    "labor_rates": LABOR_RATES_COLUMNS,
    "estimate_line_items": ESTIMATE_LINE_ITEMS_COLUMNS,
    "pricing_guide_items": PRICING_GUIDE_ITEMS_COLUMNS,
    "pricing_guide_price_history": PRICING_GUIDE_PRICE_HISTORY_COLUMNS,
    "vendors": VENDORS_COLUMNS,
    "todos": TODOS_COLUMNS,
    "time_entries": TIME_ENTRIES_COLUMNS,
    "employee_timekeeping_days": EMPLOYEE_TIMEKEEPING_DAYS_COLUMNS,
    "employee_timekeeping_weeks": EMPLOYEE_TIMEKEEPING_WEEKS_COLUMNS,
    "job_equipment": JOB_EQUIPMENT_COLUMNS,
    "job_email_settings": JOB_EMAIL_SETTINGS_COLUMNS,
    "inventory_transactions": INVENTORY_TRANSACTIONS_COLUMNS,
    "employee_documents": EMPLOYEE_DOCUMENTS_COLUMNS,
    "company_events": COMPANY_EVENTS_COLUMNS,
    "employee_certifications": EMPLOYEE_CERTIFICATIONS_COLUMNS,
    "documents_hub": DOCUMENTS_HUB_COLUMNS,
    "company_updates": COMPANY_UPDATES_COLUMNS,
    "weekly_timesheets": WEEKLY_TIMESHEETS_COLUMNS,
    "weekly_timesheet_lines": WEEKLY_TIMESHEET_LINES_COLUMNS,
    "job_daily_updates": JOB_DAILY_UPDATES_COLUMNS,
    "job_materials": JOB_MATERIALS_COLUMNS,
    "small_hand_tools": SMALL_HAND_TOOLS_COLUMNS,
    "tool_transactions": TOOL_TRANSACTIONS_COLUMNS,
    "company_settings": COMPANY_SETTINGS_COLUMNS,
    "ips_lookup_tables": IPS_LOOKUP_TABLES_COLUMNS,
    "ips_lookup_values": IPS_LOOKUP_VALUES_COLUMNS,
    "tool_trailer_kits": TOOL_TRAILER_KITS_COLUMNS,
    "asset_kit_items": ASSET_KIT_ITEMS_COLUMNS,
    "asset_kit_audits": ASSET_KIT_AUDITS_COLUMNS,
    "asset_kit_transactions": ASSET_KIT_TRANSACTIONS_COLUMNS,
    "estimate_labor_lines": ESTIMATE_LABOR_LINES_COLUMNS,
    "estimate_equipment": ESTIMATE_EQUIPMENT_COLUMNS,
    "estimate_subcontractors": ESTIMATE_SUBCONTRACTORS_COLUMNS,
    "estimate_other_costs": ESTIMATE_OTHER_COSTS_COLUMNS,
    "estimate_travel": ESTIMATE_TRAVEL_COLUMNS,
    "estimate_terms": ESTIMATE_TERMS_COLUMNS,
    "qr_scan_events": QR_SCAN_EVENTS_COLUMNS,
    "asset_inspections": ASSET_INSPECTIONS_COLUMNS,
    # Legacy standalone catalog table (pre-unified pricing guide).
    "materials_catalog": _cols(
        "id",
        "item_key",
        "description",
        "category",
        "unit",
        "unit_cost",
        "markup",
        "sell_price",
        "vendor",
        "notes",
    ),
}


def normalize_table_key(table_name: str) -> str:
    key = str(table_name or "").strip().lower()
    return TABLE_ALIASES.get(key, key)


def resolve_list_columns(table_name: str, columns: str | None) -> str:
    """
    Resolve a PostgREST ``columns`` string for list reads.

    - Explicit non-empty, non-``*`` values pass through unchanged.
    - ``*`` passes through (schema introspection only).
    - ``None`` / omitted uses ``TABLE_LIST_COLUMNS`` for the table.
    """
    if columns is not None:
        c = str(columns).strip()
        if c == "*":
            return c
        if c:
            return c
    key = normalize_table_key(table_name)
    try:
        return TABLE_LIST_COLUMNS[key]
    except KeyError as exc:
        raise ValueError(
            f"No default list columns for table {table_name!r}. "
            "Pass columns= explicitly or register the table in TABLE_LIST_COLUMNS."
        ) from exc
