"""
Selectable table rows + action bar (view / edit / delete / export).

Implementation lives in :mod:`table_actions`; this module exposes the same API under ``app.ui.action_bar``.
"""

from __future__ import annotations

try:
    from app.table_actions import (
        IPS_ACTION_BAR_CSS,
        IPS_PENDING_DELETE,
        IPS_ROW_SELECTIONS,
        TABLE_KEY_ASSETS,
        TABLE_KEY_ASSET_MANAGER,
        TABLE_KEY_CUSTOMERS,
        TABLE_KEY_EMPLOYEES,
        TABLE_KEY_EQUIPMENT,
        TABLE_KEY_ESTIMATES,
        TABLE_KEY_INVENTORY,
        TABLE_KEY_INVENTORY_SUPPLIES,
        TABLE_KEY_JOBS,
        TABLE_KEY_LABOR,
        TABLE_KEY_MATERIALS,
        TABLE_KEY_PEOPLE,
        TABLE_KEY_PO_EXPENSES,
        TABLE_KEY_TIME_ENTRIES,
        TABLE_KEY_TIMESHEETS,
        TABLE_KEY_USERS,
        clear_selected_ids,
        get_selected_ids,
        inject_table_action_styles,
        render_selectable_dataframe,
        render_selection_action_bar,
        render_table_action_bar,
        selected_row_session_key,
        set_selected_ids,
    )
except ImportError:
    from table_actions import (  # type: ignore
        IPS_ACTION_BAR_CSS,
        IPS_PENDING_DELETE,
        IPS_ROW_SELECTIONS,
        TABLE_KEY_ASSETS,
        TABLE_KEY_ASSET_MANAGER,
        TABLE_KEY_CUSTOMERS,
        TABLE_KEY_EMPLOYEES,
        TABLE_KEY_EQUIPMENT,
        TABLE_KEY_ESTIMATES,
        TABLE_KEY_INVENTORY,
        TABLE_KEY_INVENTORY_SUPPLIES,
        TABLE_KEY_JOBS,
        TABLE_KEY_LABOR,
        TABLE_KEY_MATERIALS,
        TABLE_KEY_PEOPLE,
        TABLE_KEY_PO_EXPENSES,
        TABLE_KEY_TIME_ENTRIES,
        TABLE_KEY_TIMESHEETS,
        TABLE_KEY_USERS,
        clear_selected_ids,
        get_selected_ids,
        inject_table_action_styles,
        render_selectable_dataframe,
        render_selection_action_bar,
        render_table_action_bar,
        selected_row_session_key,
        set_selected_ids,
    )

__all__ = [
    "IPS_ACTION_BAR_CSS",
    "IPS_PENDING_DELETE",
    "IPS_ROW_SELECTIONS",
    "TABLE_KEY_ASSETS",
    "TABLE_KEY_ASSET_MANAGER",
    "TABLE_KEY_CUSTOMERS",
    "TABLE_KEY_EMPLOYEES",
    "TABLE_KEY_EQUIPMENT",
    "TABLE_KEY_ESTIMATES",
    "TABLE_KEY_INVENTORY",
    "TABLE_KEY_INVENTORY_SUPPLIES",
    "TABLE_KEY_JOBS",
    "TABLE_KEY_LABOR",
    "TABLE_KEY_MATERIALS",
    "TABLE_KEY_PEOPLE",
    "TABLE_KEY_PO_EXPENSES",
    "TABLE_KEY_TIME_ENTRIES",
    "TABLE_KEY_TIMESHEETS",
    "TABLE_KEY_USERS",
    "clear_selected_ids",
    "get_selected_ids",
    "inject_table_action_styles",
    "render_selectable_dataframe",
    "render_selection_action_bar",
    "render_table_action_bar",
    "selected_row_session_key",
    "set_selected_ids",
]
